### ISSUE TITLE
Menu displaying problem

### ISSUE THREAD

**Issue by safaritn** [Astrarium/Astrarium#116] opened 2024-06-11 20:17 UTC
Hi,

When I run the program, the menu displays "{" and "}" characters !
![image](https://github.com/Astrarium/Astrarium/assets/26029048/f87d9cd3-3788-4498-9c90-ee9e636167ea)
How can I fix this problem ? Thank you.

**Comment by Atque** [comment] 2024-06-12 15:44
See #110.

**Comment by AlexanderKrutov** [comment] 2024-06-13 09:09
Closed as duplicate of #110 , see that issue for details.

**Closed by AlexanderKrutov** 2024-06-13 09:09 UTC
