### ISSUE TITLE
High CPU usage after opening eclipse map

### ISSUE THREAD

**Issue by Atque** [Astrarium/Astrarium#115] opened 2024-06-06 08:08 UTC
After using the eclipse map, my CPU continues to run with a higher-than-usual load, about 11%. What's worse is that it appears to add up the more I open and close the eclipse map; after two uses, the CPU load stays at roughly 21%, three times at 27% etc. Restarting Astrarium is the only solution I have found.

I have an AMD Ryzen 7 3700X if this is a hardware-specific issue.

**Comment by AlexanderKrutov** [comment] 2024-06-11 07:39
Thanks for the issue report. I could not reproduce the problem (no CPU highload on my environment), but found that some worker threads not finalizing properly after using the eclipse tool. That may be a reason. I did required fixes, hope it helps. The fix will be incuded in the upcoming release.

**Closed** 2024-09-10 10:34 UTC
Labels: bug
